spring:
  batch:
    job:
      enabled: false
  shell:
    interactive:
      enabled: true

  data:
    mongodb:
      uri: mongodb://localhost
      port: 0
      database: SpringBatchDB

app:
  output-file: output.dat

