DROP TABLE IF EXISTS GENRES;
DROP TABLE IF EXISTS AUTHORS;
DROP TABLE IF EXISTS BOOKS;
CREATE table GENRES  (ID BIGSERIAL PRIMARY KEY, NAME VARCHAR(255));
CREATE table AUTHORS (ID BIGSERIAL PRIMARY KEY, FIRSTNAME VARCHAR(255), SECONDNAME VARCHAR(255), LASTNAME VARCHAR(255), BIRTHDATE DATE);
CREATE TABLE BOOKS(ID BIGSERIAL PRIMARY KEY, NAME VARCHAR(255), GENREID BIGINT, AUTHORId BIGINT, FOREIGN KEY  (AUTHORId) REFERENCES AUTHORS(ID),FOREIGN KEY  (GENREId) REFERENCES GENRES(ID) );
